### PR TITLE
Add Queue and Message, Update aws-sdk

### PR DESCRIPTION
**Pull request by sschepens**
#83 
Added simple Queue and Message implementations which provide all the functionallity needed by Shoryuken itself, maybe needs some more methods, but i cant find documentation for old versions of v2.
This implementations allows for unlocking aws-sdk versions and use latest.

All tests pass and tested locally with a queue and worked just fine.

Cheers,
Sebastian

### CODE REVIEW

**Comment by phstc** [comment]
Thanks @sschepens!  Let me check with @leemhenson, because he worked on something message/queue before.

Hey @leemhenson, is that similar to what you have for message & queue? Will these changes work for you as well?

**Comment by leemhenson** [comment]
What's changed since https://github.com/phstc/shoryuken/pull/39 ? The consensus then was that we would pin to 2.0.21 of aws-sdk rather than reimplementing the missing resources.

**Comment by phstc** [comment]
> The consensus then was that we would pin to 2.0.21 of aws-sdk

I agree with that. But it seems that aws-sdk is taking long to add these resources back, even being a [priority](https://forums.aws.amazon.com/thread.jspa?threadID=172341&tstart=0).

I'm not 100% sure on having these implemented in Shoryuken, but aws-sdk releases a version every week https://github.com/aws/aws-sdk-ruby/blob/master/CHANGELOG.md (usually more than one per week)

What are your thoughts on that? Let's keep those like our previous consensus or add them? Will that be useful for you?

**Comment by leemhenson** [comment]
I'm happy either way as long as it's not a API breaking change.

**Comment by phstc** [comment]
Added to master :beers:

**Comment by sschepens** [comment]
Thanks for merging this guys! as soon as aws-sdk adds it's own implementations we can revert this :smile:

**Pull request merged**
