### PR TITLE
Try to fix auto visibility problem after  "Removed use of defer"

### PR DESCRIPTION
**Pull request by phstc**
Related https://github.com/phstc/shoryuken/pull/104#issuecomment-109044536

### CODE REVIEW

**Comment by gshutler** [comment]
Hey @phstc I don't know Celluloid well enough yet to know if using an actor is a good idea or not, I'll read up on it though. However, if it is the right approach I think the actor should probably be lazily initialized as creating it creates a thread and many consumers probably don't use the feature.

I've made the changes for that, along with some other little tweaks on my fork [git compare](https://github.com/phstc/shoryuken/compare/master...gshutler:no-defer) as it was a bit hard to explain in comments alone.

**Comment by phstc** [comment]
@gshutler I like what you did! :smile: I re-opened #104, could you push these changes to `gshutler:no-defer` to auto update your PR?

**Comment by phstc** [comment]
Thanks @leemhenson. I agree with you :smile: 

I was just worried on introducing a new actor `MessageVisiblity`, this part is not available in Sidekiq, it's specific to Shoryuken.

**Comment by gshutler** [comment]
Looks like the changes are already there, I did them on the same branch.

**Comment by phstc** [comment]
Closing in favor of #104

**Pull request closed without merging**
