### PR TITLE
Fix error when initialize shoryuken daemonize

### PR DESCRIPTION
**Pull request by purintai**
repro
```bundle exec shoryuken -d -L ./log/shoryuken.log```

### CODE REVIEW

**Comment by mariokostelac** [comment]
Hi @purintai, thanks for the contribution. Could you give us a little bit of context?

**Comment by purintai** [comment]
@mariokostelac 

When initializing shoryuken:
First, run bin/shoryuken and `require_relative '../lib/shoryuken/cli'`
then `require 'shoryuken'` in [lib/shoryuken/cli.rb](https://github.com/phstc/shoryuken/blob/v2.0.7/lib/shoryuken/cli.rb#L7)
then `require 'shoryuken/middleware/server/auto_extend_visibility'` in [lib/shoryuken.rb](https://github.com/phstc/shoryuken/blob/v2.0.7/lib/shoryuken.rb#L18)
then `require 'celluloid'` in [lib/shoryuken/middleware/server/auto_extend_visibility.rb](https://github.com/phstc/shoryuken/blob/v2.0.7/lib/shoryuken/middleware/server/auto_extend_visibility.rb#L1)
at last. if shoryuken running with daemonize option, [IT FAIL.](https://github.com/phstc/shoryuken/blob/v2.0.7/lib/shoryuken/cli.rb#L67)

repro log
```
[deploy@ip-10-12-34-56 my-rails-project]$ bundle exec shoryuken -d -L ./log/shoryuken.log 
I, [2016-06-07T10:03:21.936894 #849]  INFO -- : Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
2016-06-07T10:03:21Z 849 TID-gq0lemk38 WARN: No queues supplied
Celluloid cannot be required until here, or it will break Shoryuken's daemonization
/var/www/my-rails-project/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.7/lib/shoryuken/cli.rb:67:in `load_celluloid'
/var/www/my-rails-project/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.7/lib/shoryuken/cli.rb:39:in `run'
/var/www/my-rails-project/vendor/bundle/ruby/2.3.0/gems/shoryuken-2.0.7/bin/shoryuken:6:in `<top (required)>'
/var/www/my-rails-project/vendor/bundle/ruby/2.3.0/bin/shoryuken:23:in `load'
/var/www/my-rails-project/vendor/bundle/ruby/2.3.0/bin/shoryuken:23:in `<top (required)>'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/usr/local/rbenv/versions/2.3.1/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
[deploy@ip-10-12-34-56 my-rails-project]$ 
```

**Comment by mariokostelac** [comment]
That does not work either:
```
NameError: uninitialized constant #<Class:0x005627b92110b0>::Celluloid
  /apps/intercom/shoryuken/lib/shoryuken/middleware/server/auto_extend_visibility.rb:19:in `<class:MessageVisibilityExtender>'
  /apps/intercom/shoryuken/lib/shoryuken/middleware/server/auto_extend_visibility.rb:18:in `<class:AutoExtendVisibility>'
  /apps/intercom/shoryuken/lib/shoryuken/middleware/server/auto_extend_visibility.rb:4:in `<module:Server>'
  /apps/intercom/shoryuken/lib/shoryuken/middleware/server/auto_extend_visibility.rb:3:in `<module:Middleware>'
  /apps/intercom/shoryuken/lib/shoryuken/middleware/server/auto_extend_visibility.rb:2:in `<module:Shoryuken>'
  /apps/intercom/shoryuken/lib/shoryuken/middleware/server/auto_extend_visibility.rb:1:in `<top (required)>'
  /apps/intercom/shoryuken/lib/shoryuken.rb:18:in `require'
  /apps/intercom/shoryuken/lib/shoryuken.rb:18:in `<top (required)>'
  /apps/intercom/shoryuken/lib/shoryuken/cli.rb:7:in `require'
  /apps/intercom/shoryuken/lib/shoryuken/cli.rb:7:in `<top (required)>'
  /apps/intercom/shoryuken/bin/shoryuken:3:in `require_relative'
  /apps/intercom/shoryuken/bin/shoryuken:3:in `<top (required)>'
  /bundler_cache/bin/shoryuken:22:in `load'
  /bundler_cache/bin/shoryuken:22:in `<top (required)>'
```

**Comment by purintai** [comment]
Trying plan B. (require to autoload in lib/shoryuken.rb)

**Comment by mariokostelac** [comment]
@purintai can we just invest in better detection if Celluloid is running?

**Comment by mariokostelac** [comment]
Ok, Celluloid is already running at that point.

**Comment by purintai** [comment]
CI build failed with no luck....
Could you rebuild it?

**Comment by mariokostelac** [comment]
Could we also move `load_celluloid` before loading an environment like I did in https://github.com/phstc/shoryuken/pull/222?
That will also retrigger the build.

**Comment by mariokostelac** [comment]
Hi @purintai, I've carried your commit to https://github.com/phstc/shoryuken/pull/223 so I can merge as fast as I can.

**Comment by curious-core** [comment]
Thanks.

**Comment by mariokostelac** [comment]
New version is released. Thank you once more.

**Comment by purintai** [comment]
sounds great, thanks!

**Pull request closed without merging**
