### PR TITLE
fix all the specs that I broke in a somewhat cavalier fashion

### PR DESCRIPTION
**Pull request by leemhenson**
er, yeah. :blush:

### CODE REVIEW

**Comment by phstc** [comment]
hehe tks :beers: 

let's see if it will pass merged into master :pray:

**Comment by leemhenson** [comment]
I think these tests are pretty valuable to be honest. I think we should try to get them running. I suppose we could do something like setting up each test to avoid crosstalk by uniquely identify it's own messages, but that would make writing tests pretty ugly.

**Comment by leemhenson** [comment]
Annoying that this has failed:

https://travis-ci.org/phstc/shoryuken/builds/52414881

Can you try sleeping longer here? https://github.com/phstc/shoryuken/blob/master/spec/integration/launcher_spec.rb#L105

**Comment by kookster** [comment]
hey @leemhenson @phstc this is great.

There are also incorrect `find_message` calls in `Rakefile` and `active_job_adapter.rb`
Do you want me to put in a different PR for fixing those?

**Pull request merged**
